const arr1 = [
    { id: 1, description: "大展鸿图，信用得固，无远弗界，可获成功", evaluation: "吉" },
    { id: 2, description: "根基不固，摇摇欲坠，一盛一衰，劳而无功", evaluation: "凶" },
    { id: 3, description: "根深蒂固，蒸蒸日上，如意吉祥，百事顺遂", evaluation: "吉" },
    { id: 4, description: "坎坷前途，苦难折磨，非有毅力，难望成功", evaluation: "凶" },
    { id: 5, description: "阴阳和合，生意欣荣，名利双收，后福重重", evaluation: "吉" },
    { id: 6, description: "万宝云集，天降幸运，立志奋发，可成大功", evaluation: "吉" },
    { id: 7, description: "专心经营，和气致祥，排除万难，必获成功", evaluation: "吉" },
    { id: 8, description: "努力发达，贯彻志望，不忘进退，成功可期", evaluation: "吉" },
    { id: 9, description: "虽抱奇才，有才无命，独营无力，财利无望", evaluation: "凶" },
    { id: 10, description: "乌云遮月，暗淡无光，空费心力，徒劳无功", evaluation: "凶" },
    { id: 11, description: "草木逢春，枯叶沾露，稳健着实，必得人望", evaluation: "吉" },
    { id: 12, description: "薄弱无力，孤立无摇，外祥内苦，谋事难成", evaluation: "凶" },
    { id: 13, description: "天赋吉运，能得人望，善用智慧，必获成功", evaluation: "吉" },
    { id: 14, description: "忍得苦难，必有后福，是成是败，惟靠坚毅", evaluation: "凶" },
    { id: 15, description: "谦恭做事，必得人和，大事成就，一定兴隆", evaluation: "吉" },
    { id: 16, description: "能获众望，成就大业，名利双收，盟主四方", evaluation: "吉" },
    { id: 17, description: "排除万难，有贵人助，把握时机，可得成功", evaluation: "吉" },
    { id: 18, description: "经商做事，顺利昌隆，如能慎始，百事亨通", evaluation: "吉" },
    { id: 19, description: "成功虽早，慎防空亏，内外不合，障碍重重", evaluation: "凶" },
    { id: 20, description: "智高志大，历尽艰难，焦心忧劳，进退两难", evaluation: "凶" },
    { id: 21, description: "专心经营，善用智慧，霜雪梅花，春来怒放", evaluation: "吉" },
    { id: 22, description: "秋草逢霜，怀才不遇，忧愁怨苦，事不如意", evaluation: "凶" },
    { id: 23, description: "旭日升天，名显四方，渐次进展，终成大业", evaluation: "吉" },
    { id: 24, description: "锦绣前程，须靠自力，多用智谋，能奏大功", evaluation: "吉" },
    { id: 25, description: "天时地利，再得人格，讲信修睦，即可成功", evaluation: "吉" },
    { id: 26, description: "波澜起伏，千变万化，凌驾万难，必可成功", evaluation: "凶" },
    { id: 27, description: "一成一败，一盛一衰，惟靠谨慎，可守成功", evaluation: "凶带吉" },
    { id: 28, description: "鱼临旱地，难逃恶运，此数大凶，不如更名", evaluation: "凶" },
    { id: 29, description: "如龙得云，青云直上，智谋奋进，才略奏功", evaluation: "吉" },
    { id: 30, description: "吉凶参半，得失相伴，投机取巧，如赛一样", evaluation: "凶" },
    { id: 31, description: "此数大吉，名利双收，渐进向上，大业成就", evaluation: "吉" },
    { id: 32, description: "池中之龙，风云际会，一跃上天，成功可望", evaluation: "吉" },
    { id: 33, description: "不可意气，善用智慧，如能慎始，必可昌隆", evaluation: "吉" },
    { id: 34, description: "灾难不绝，难望成功，此数大凶，不如更名", evaluation: "凶" },
    { id: 35, description: "中吉之数，进退保守，生意安稳，成就可期", evaluation: "吉" },
    { id: 36, description: "波澜重迭，常陷穷困，动不如静，有才无命", evaluation: "凶" },
    { id: 37, description: "逢凶化吉，吉人天相，风条雨顺，生意兴隆", evaluation: "吉" },
    { id: 38, description: "名虽可得，利则难获，艺界发展，可望成功", evaluation: "凶带吉" },
    { id: 39, description: "云开见月，虽有劳碌，光明坦途，指日可期", evaluation: "吉" },
    { id: 40, description: "一胜一衰，浮沉不定，知难而退，自获天佑", evaluation: "吉带凶" },
    { id: 41, description: "天赋吉运，德望兼备，继续努力，前途无限", evaluation: "吉" },
    { id: 42, description: "事业不专，十九不成，专心进取，可望成功", evaluation: "吉带凶" },
    { id: 43, description: "雨夜之花，外祥内苦，忍耐自重，转凶为吉", evaluation: "吉带凶" },
    { id: 44, description: "虽用心计，事难遂愿，贪功好进，必招失败", evaluation: "凶" },
    { id: 45, description: "杨柳遇春，绿叶发枝，冲破难关，一举成名", evaluation: "吉" },
    { id: 46, description: "坎坷不平，艰难重重，若无耐心，难望有成", evaluation: "凶" },
    { id: 47, description: "有贵人助，可成大业，虽遇不幸，浮沉不大", evaluation: "吉" },
    { id: 48, description: "美化丰实，鹤立鸡群，名利俱全，繁荣富贵", evaluation: "吉" },
    { id: 49, description: "遇吉则吉，遇凶则凶，惟靠谨慎，逢凶化吉", evaluation: "凶" },
    { id: 50, description: "吉凶互见，一成一败，凶中有吉，吉中有凶", evaluation: "吉带凶" },
    { id: 51, description: "一盛一衰，浮沉不常，自重自处，可保平安", evaluation: "吉带凶" },
    { id: 52, description: "草木逢春，雨过天晴，渡过难关，即获成功", evaluation: "吉" },
    { id: 53, description: "盛衰参半，外祥内苦，先吉后凶，先凶后吉", evaluation: "吉带凶" },
    { id: 54, description: "虽倾全力，难望成功，此数大凶，最好改名", evaluation: "凶" },
    { id: 55, description: "外观隆昌，内隐祸患，克服难关，开出泰运", evaluation: "吉带凶" },
    { id: 56, description: "事与愿违，终难成功，欲速不达，有始有终", evaluation: "凶" },
    { id: 57, description: "努力经营，时来运转，旷野枯草，春来花开", evaluation: "吉" },
    { id: 58, description: "半凶半吉，浮沉多端，始凶终吉，能保成功", evaluation: "凶带吉" },
    { id: 59, description: "遇事犹疑，难望成事，大刀阔斧，始可有成", evaluation: "凶" },
    { id: 60, description: "黑暗无光，心迷意乱，出尔反尔，难定方针", evaluation: "凶" },
    { id: 61, description: "云遮半月，百隐风波，应自谨慎，始保平安", evaluation: "吉带凶" },
    { id: 62, description: "烦闷懊恼，事事难展，自防灾祸，始免困境", evaluation: "凶" },
    { id: 63, description: "万物化育，繁荣之象，专心一意，始能成功", evaluation: "吉" },
    { id: 64, description: "见异思迁，十九不成，徒劳无功，不如更名", evaluation: "凶" },
    { id: 65, description: "吉运自来，能享盛名，把握机会，必获成功", evaluation: "吉" },
    { id: 66, description: "黑夜漫长，进退维谷，内外不合，信用缺乏", evaluation: "凶" },
    { id: 67, description: "时来运转，事事如意，功成名就，富贵自来", evaluation: "吉" },
    { id: 68, description: "思虑周详，计划力行，不失先机，可望成功", evaluation: "吉" },
    { id: 69, description: "动摇不安，常陷逆境，不得时运，难得利润", evaluation: "凶" },
    { id: 70, description: "惨淡经营，难免贫困，此数不吉，最好改名", evaluation: "凶" },
    { id: 71, description: "吉凶参半，惟赖勇气，贯彻力行，始可成功", evaluation: "吉带凶" },
    { id: 72, description: "利害混集，凶多吉少，得而复失，难以安顺", evaluation: "凶" },
    { id: 73, description: "安乐自来，自然吉祥，力行不懈，终必成功", evaluation: "吉" },
    { id: 74, description: "利不及费，坐食山空，如无智谋，难望成功", evaluation: "凶" },
    { id: 75, description: "吉中带凶，欲速不达，进不如守，可保安详", evaluation: "吉带凶" },
    { id: 76, description: "此数大凶，破产之象，宜速改名，以避厄运", evaluation: "凶" },
    { id: 77, description: "先苦后甘，先甘后苦，如能守成，不致失败", evaluation: "吉带凶" },
    { id: 78, description: "有得有失，华而不实，须防劫财，始保平安", evaluation: "吉带凶" },
    { id: 79, description: "如走夜路，前途无光，希望不大，劳而无功", evaluation: "凶" },
    { id: 80, description: "得而复失，枉费心机，守成无贪，可保安稳", evaluation: "吉带凶" },
    { id: 81, description: "最极之数，还本归元，能得繁业，发达成功", evaluation: "吉" }
  ];

  const arr2 = [
    {
        "number": "1",
        "description": "宇宙起源，天地开泰之太极首领数",
        "status": "大吉",
        "hidden_info": "繁荣发达，大展鸿图，信用得固，万人仰望，无远弗界，可获成功",
        "shici": "天地开泰万事成，身体康安亦富荣，否泰名誉兼享福，一生无忧乐绵长。",
        "star": 6,
        "jianyi": "顺风满帆而容易有所成就，易取富贵人生。",
        "result": "吉",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "2",
        "description": "混饨未定，进退失据之分离落败数",
        "status": "凶",
        "hidden_info": "动摇不安，根基不固，摇摇欲坠，一荣一枯，一盛一衰，劳而无功",
        "shici": "混吨未定如萍动，乱离不安亦波浪，独立无力多遇困，无欲无求寿可延。",
        "star": 2,
        "jianyi": "与人合伙比之独营好得多，若自己独营商则中途易受挫折。",
        "result": "凶",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "3",
        "description": "进取如意之增进繁荣数",
        "status": "大吉",
        "hidden_info": "立身处世，有贵人助，根深蒂固，蒸蒸日上，天赐吉祥，百事顺遂，四海扬名",
        "shici": "进取富贵又如意，智达明敏扬名威，名利寿福皆此得，前途光茫好鸿图。",
        "star": 6,
        "jianyi": "外缘殊胜，容易得人之助力及予人好印象。",
        "result": "吉",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "4",
        "description": "破败汹变，万事休止之放荡数",
        "status": "凶",
        "hidden_info": "日被云遮，坎坷前途，苦难折磨，非有毅力，难望成功",
        "shici": "溯体汹变不具整，果落枝折病难多，山空鸟飞祸惑频，苦苦之中有孝人。",
        "star": 2,
        "jianyi": "营商的话还是独营的好，与人合伙久之厌烦不耐。少年读书需用心，舟至桥头直自然。",
        "result": "凶",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "5",
        "description": "福禄长寿之福德集门数",
        "status": "大吉",
        "hidden_info": "阴阳和合，精神愉快，生意欣荣，荣誉达利，名利双收，一门兴隆，后福重重",
        "shici": "福禄寿长阴阳和，心身健全是英豪，名利双收富荣达，乃是世上福德人。",
        "star": 6,
        "jianyi": "财源特佳金钱有餘，离出生之地而往大都市求谋必得更发达。",
        "result": "吉",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "6",
        "description": "安稳余庆之吉人天相数",
        "status": "中吉",
        "hidden_info": "万宝集门，天降幸运，立志奋发，得成大业",
        "shici": "安稳余庆福禄开，盛大幸福天赐来，内含衰兆应谨慎，注意品行福乐享。",
        "star": 5,
        "jianyi": "名誉良好，信用亦佳，步步高升。",
        "result": "吉",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "7",
        "description": "刚毅果断之勇往直前之全般整理进取数",
        "status": "中吉",
        "hidden_info": "精力旺盛，头脑明敏，专心经营，和气致祥，排除万难，必获成功",
        "shici": "刚毅果断除万难，独立权威志气安，内外和好兼柔性，温和养德耀吉星。",
        "star": 5,
        "jianyi": "很勤勉求上进，又很有耐力，在技术界或艺能界，是最可能成功之数也。但此数因少得人和，而略感孤独些。",
        "result": "吉",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "8",
        "description": "意志刚健之勤勉发展数",
        "status": "中吉",
        "hidden_info": "努力发达，贯彻意愿，不忘进退，可期成功",
        "shici": "意志坚刚善恶明，富进取心求和平，忍耐克己如心意，前难后成可安然。",
        "star": 5,
        "jianyi": "很勤勉求上进，又很有耐力，在技术界或艺能界，是最可能成功之数也。但此数因少得人和，而略感孤独些。",
        "result": "吉",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "9",
        "description": "兴尽入凶之穷乏困苦数",
        "status": "大凶",
        "hidden_info": "虽抱奇才，伯乐何在，独营无力，财利难望",
        "shici": "兴尽凶始遇困途，穷厄是非亲怙苦，海枯石烂心凉悲，无有恐怖无所惧。",
        "star": 1,
        "jianyi": "因异性而引起之纠纷困扰，失利特多，而且一生常遇逆境之折磨。家庭和顺则万事可成。切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "10",
        "description": "万事终局之易损耗数",
        "status": "大凶",
        "hidden_info": "乌云遮月，暗淡无光，空费心力，徒劳无功",
        "shici": "万事终局万事空，逆难失意逢了忘，体弱灯暗居风破，无求所欲或复还。",
        "star": 1,
        "jianyi": "吉星甚少眷顾，且易累及他人，有浪费金钱之倾向，倒楣星君，需要注重修炼个人德行，以免因此受累。家庭和顺则可万事成。切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "11",
        "description": "富贵荣达，稳健吉右，挽回家运之外缘殊胜数",
        "status": "大吉",
        "hidden_info": "草木逢春，枝叶沾露，稳健着实，必得人望",
        "shici": "挽回家运矣春光，顺调发展财辉煌，温和笃实阴阳合，稳健顺调得人望。",
        "star": 6,
        "jianyi": "顺风满帆而容易有所成就，易取富贵人生。外缘殊胜，容易得人之助力及予人好印象。",
        "result": "吉",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "12",
        "description": "意志薄弱之家庭寂寞数",
        "status": "凶",
        "hidden_info": "薄弱无力，孤立无摇，外祥内苦，谋事难成",
        "shici": "意志薄弱不伸长，易招失败遇厄栽，家属缘薄人孤独，安居守份保平安。",
        "star": 2,
        "jianyi": "与人合伙比之独营好得多，若自己独营商则中途挫折。切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "13",
        "description": "智略超群，博学多才之技能成功数",
        "status": "大吉",
        "hidden_info": "天赋吉运，能得人望，善用智慧，必获成功",
        "shici": "智略超群博学多，善处事务亦忍和，功业成就得富荣，艺才相身乐千锺。",
        "star": 6,
        "jianyi": "外缘殊胜，容易得人之助力及予人好印象。具有此数之人，男多勇敢果断，女多貌若天仙，有风流不羁(不顾时局大体)倾向，若修养不够或抑制力不强，往往因桃色事件惹来麻烦。",
        "result": "吉",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "14",
        "description": "天涯沦落之失意闷烦数",
        "status": "大凶",
        "hidden_info": "忍得苦难，必有后福，是成是败，惟靠坚毅",
        "shici": "天涯泪落失怙恃，族家缘薄易克缘，寂寞烦闷易灾厄，独身浮沉难可栖。",
        "star": 1,
        "jianyi": "营商的话还是独营的好，与人合伙久之厌烦不耐。少年读书需用心，舟至桥头直自然。",
        "result": "凶",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "15",
        "description": "福寿双全之立身兴家数",
        "status": "大吉",
        "hidden_info": "谦恭做事，必得人和，大事成就，一门兴隆",
        "shici": "福寿拱照德望高，财子寿全又温和，慈祥好善可恭敬，富贵繁荣得惠泽。",
        "star": 6,
        "jianyi": "财源特佳金钱有餘，离出生之地而往大都市求谋必得更发达。外缘殊胜，容易得人之助力及予人好印象。",
        "result": "吉",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "16",
        "description": "贵人相助，兴家兴业之名利聚身数",
        "status": "大吉",
        "hidden_info": "能获众望，成就大业，名利双收，盟主四方",
        "shici": "贵人得助天乙扶，为人之上有财富，众望所归事业成，不可贪色保安宁。",
        "star": 6,
        "jianyi": "名誉良好，信用亦佳，步步高升。外缘殊胜，容易得人之助力及予人好印象。",
        "result": "吉",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "17",
        "description": "突破万难之刚柔兼备数",
        "status": "中吉",
        "hidden_info": "排除万难，有贵人助，把握时机，可得成功",
        "shici": "突破万难权威高，刚性固执如英豪，须事谨慎守和平，可得大功奏业成。",
        "star": 5,
        "jianyi": "很勤勉求上进，又很有耐力，在技术界或艺能界，是最可能成功之数也。但此数因少得人和，而略感孤独些。",
        "result": "吉",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "18",
        "description": "有志竟成之内名有运数",
        "status": "中吉",
        "hidden_info": "经商做事，顺利昌隆，如能慎始，百事亨通",
        "shici": "有志竟成事皆通，智谋发展有威望，过刚遭难咸柔德，博得名利大成功。",
        "star": 5,
        "jianyi": "很勤勉求上进，又很有耐力，在技术界或艺能界，是最可能成功之数也。但此数因少得人和，而略感孤独些。",
        "result": "吉",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "19",
        "description": "反应机敏，风云蔽月，先声夺人之厄困重来数",
        "status": "大凶",
        "hidden_info": "成功虽早，慎防空亏，内外不合，障碍重重",
        "shici": "风云蔽月末得安，虽有智能作事难，孤困不和损近缘，远离颠倒无所失。",
        "star": 1,
        "jianyi": "因异性而引起之纠纷困扰，失利特多，而且一生常遇逆境之折磨。家庭和顺则万事可成。切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "20",
        "description": "实而不华，深藏不露，非业破运之祸厄不安数",
        "status": "大凶",
        "hidden_info": "智高志大，历尽艰难，焦心忧劳，进退两难",
        "shici": "非业破运困害重，厄难病弱频频恐，一生难得安宁时，远离颠倒失复还。",
        "star": 1,
        "jianyi": "吉星甚少眷顾，且易累及他人，有浪费金钱之倾向，倒楣星君，需要注重修炼个人德行，以免因此受累。家庭和顺则可万事成。切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "21",
        "description": "明月中天，质实刚健之独立权威数",
        "status": "大吉",
        "hidden_info": "专心经营，善用智慧，霜雪梅花，春来怒放",
        "shici": "明月光照乐依依，俟如梅花待放时，兴家立业名利全，各自独立有权威。",
        "star": 6,
        "jianyi": "男带此数，需要加强节制力，可免受桃花困扰。女则因事业雄心万丈，多晚婚。",
        "result": "吉",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "22",
        "description": "秋草逢霜，两士相争之忧愁怨苦数",
        "status": "凶",
        "hidden_info": "秋草逢霜，怀才不济，忧愁怨苦，事难如意",
        "shici": "秋草逢霜不如意，不平不满却难依，逆境挫折意志薄，身世凋冷心操劳。",
        "star": 2,
        "jianyi": "与人合伙比之独营好得多，若自己独营商则中途挫折。中年需要注意健康，以免被疾病拖累前程。不耐寂寞。切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "23",
        "description": "旭日东升，质实刚坚之发育茂盛数",
        "status": "大吉",
        "hidden_info": "旭日升天，名显四方，渐次进展，终成大业",
        "shici": "旭日东昇势壮富，贯彻大业万事胜，终至荣达功名显，猛虎添翼势声强。",
        "star": 6,
        "jianyi": "具有此数之人，男多勇敢果断，女多貌若天仙，有风流不羁(不顾时局大体)倾向，若修养不够或抑制力不强，往往因桃色事件惹来麻烦。",
        "result": "吉",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "24",
        "description": "家门余庆之金钱丰盈数",
        "status": "大吉",
        "hidden_info": "锦绣前程，须靠自力，多用智谋，能奏大功",
        "shici": "家门余庆福无疆，子孙繁荣富贵强，白手成家立大业，财源广进智谋全。",
        "star": 6,
        "jianyi": "营商的话还是独营的好，与人合伙久之厌烦不耐。少年读书需用心，舟至桥头直自然。",
        "result": "吉",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "25",
        "description": "英俊刚毅之资性聪敏数",
        "status": "中吉",
        "hidden_info": "天时地利，只欠人和，讲信修睦，即可成功",
        "shici": "资性英敏有奇能，怪癖不和害前程，修身涵养与仁和，奏功获得大鸿图。",
        "star": 5,
        "jianyi": "需要注重个人私生活，可免因桃色韵事贻误前程。",
        "result": "吉",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "26",
        "description": "变怪异奇，艰难苦闷之豪侠数",
        "status": "凶多于吉",
        "hidden_info": "波澜起伏，千变万化，凌驾万难，必可成功",
        "shici": "千变万化慧悟高，历尽沧桑曲折多，离乱艰难缠身苦，凌驾万难始成功。",
        "star": 3,
        "jianyi": "雄心万丈，抱负壮大，有取天下而名扬八方之可能性，但反之也可能输得何其壮烈。特别需要注意个人德行修炼，免因桃花事件影响运程。",
        "result": "凶",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "27",
        "description": "足智多谋，欲望无止，盛衰争衡，先苦后甜数",
        "status": "吉多于凶",
        "hidden_info": "一成一败，一盛一衰，惟靠谨慎，可守成功",
        "shici": "迎新去旧无限度，批离中折亦多劳，欲望无止难满足，矫正自省终富荣。",
        "star": 4,
        "jianyi": "喜新厌旧，与异性交际之手段高明，是个调情专家。切忌沉迷投机，可免贻误前程。",
        "result": "凶带吉",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "28",
        "description": "自豪生离，亲缘浅薄，离群独处无定数",
        "status": "大凶",
        "hidden_info": "鱼临旱地，易遇困厄，表相汹凶，回头上岸",
        "shici": "自豪生离终辛苦，遭遇不安奈何渡，同巢雀散造敌城，远离颠倒善果期。",
        "star": 1,
        "jianyi": "尤需注意安全，可免受意外之伤害。家庭和顺则可万事成。",
        "result": "凶",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "29",
        "description": "智谋兼备，欲望难足数",
        "status": "大吉",
        "hidden_info": "如龙得云，青云直上，智谋奋进，才略奏功",
        "shici": "欲望难足希望高，计谋成功财力豪，猜疑嫉妒性自改，如龙乘云势运开。",
        "star": 6,
        "jianyi": "智能超人贯彻大志，富贵无比，不甘寂寞，叱吒风云之大吉数，但容易发生牢骚及贪心、欲望太多而永不知足，为其缺点。切忌沉迷投机，可免贻误前程。",
        "result": "吉",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "30",
        "description": "一成一败，绝处逢生，吉凶相伴之浮沉多端数",
        "status": "吉多于凶",
        "hidden_info": "吉凶参半，得失相伴，投机取巧，如赛一样",
        "shici": "绝处逢生危险多，投机浮沉受厄殃，处事细虑保安然，破釜沉舟功可成。",
        "star": 4,
        "jianyi": "切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "31",
        "description": "智勇得志，心想事成数",
        "status": "大吉",
        "hidden_info": "此数大吉，名利双收，渐进向上，大业成就",
        "shici": "智勇得志意气新，建立声誉事业兴，终到富贵福禄奏，为人领导德望高。",
        "star": 6,
        "jianyi": "顺风满帆而容易有所成就，易取富贵人生。",
        "result": "吉",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "32",
        "description": "权贵显达，困龙待机之意外惠泽数",
        "status": "中吉",
        "hidden_info": "池中之龙，风云际会，一跃上天，成功可望",
        "shici": "侥倖所得贵人扶，善捉机会有财富，认真努力向前程，家门隆昌得富荣。",
        "star": 5,
        "jianyi": "与人合伙比之独营好得多，若自己独营商则中途易受挫折。",
        "result": "吉",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "33",
        "description": "家门隆昌，才德开展之威震天下数",
        "status": "大吉",
        "hidden_info": "意气用事，人和必失，善用智慧，如能慎始，必可昌隆",
        "shici": "家门隆昌精神爽，博得名利星月朗，权威智谋极周全，君是天下富贵翁。",
        "star": 6,
        "jianyi": "具有此数之人，男则勇敢果断，女多貌若天仙，有风流不羁(不顾时局大体)倾向，若修养不够或抑制力不强，往往因桃色事件惹来麻烦。",
        "result": "吉",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "34",
        "description": "出入生死之财命难过数",
        "status": "大凶",
        "hidden_info": "厄困不绝，难望成功，表相汹凶，回头是岸",
        "shici": "山空鸟绝树枯老，千困百难波浪多，恰逢非星尤堪忧，能掉头时宜掉头。",
        "star": 1,
        "jianyi": "营商的话还是独营的好，与人合伙久之厌烦不耐。少年读书需用心，舟至桥头直自然。中年需要注意健康，以免被疾病拖累前程。不耐寂寞。",
        "result": "凶",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "35",
        "description": "温和平静之优雅发展数",
        "status": "中吉",
        "hidden_info": "处事严谨，进退保守，学智兼备，生意安稳，成就非凡",
        "shici": "温和平安艺才高，努力前途福运来，文笔奇绝仁德高，务实稳健掌门人。",
        "star": 5,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "36",
        "description": "风浪不息，侠义薄运，穷困厄难之倒楣多端数",
        "status": "大凶",
        "hidden_info": "波澜重叠，常陷穷困，动不如静，怀才难遇",
        "shici": "风浪不静难得安，侠情波澜万事难，须养精神与考虑，不可自作风头儿。",
        "star": 1,
        "jianyi": "雄心万丈，抱负壮大，有取天下而名扬八方之可能性，但反之也可能输得何其壮烈。",
        "result": "凶",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "37",
        "description": "权威显达，德望成功之吉人天相数",
        "status": "中吉",
        "hidden_info": "逢凶化吉，吉人天相，风条雨顺，生意兴隆，以德取众，必成大功",
        "shici": "权威显达得众望，忠实热诚运极旺，大德奏功无难事，终得富荣乐千锺。",
        "star": 5,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "38",
        "description": "磨铁成针，刻意经营，技艺成名之特有意义数",
        "status": "中吉",
        "hidden_info": "名虽可得，利则难获，艺界发展，可望成功",
        "shici": "意志薄弱无威望，长于技艺得长风，名可得而利难获，贯彻努力成大功。",
        "star": 5,
        "jianyi": "",
        "result": "凶带吉",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "39",
        "description": "富贵荣华，变化无穷之三士同盟数",
        "status": "大吉",
        "hidden_info": "云开见月，虽有劳碌，光明坦途，指日可期",
        "shici": "富贵荣华实可当，光明荣达好儿郎，家门隆昌福万千，世代子孙个个贤。",
        "star": 6,
        "jianyi": "因异性而引起之纠纷困扰，失利特多，而且一生常遇逆境之折磨。家庭和顺则万事可成。智能超人贯彻大志，富贵无比，不甘寂寞，叱吒风云之大吉数。切忌牢骚、贪心、欲望太多、永不知足影响前程。",
        "result": "吉",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "40",
        "description": "豪胆迈进，盛衰不定之谨慎保安数",
        "status": "吉多於凶",
        "hidden_info": "一胜一衰，浮沉不定，知难而退，自获天佑",
        "shici": "谨慎保安勿自骄，智谋胆略得显晓，知难而退获天佑，妄进逞强败涂地。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "41",
        "description": "德高望重，忠爱坚实之事事如意数",
        "status": "大吉",
        "hidden_info": "天赋吉运，德望兼备，继续努力，前途无限",
        "shici": "德望高大名誉振，才谋健全财源进，富贵荣华福禄至，前途洋洋得意真。",
        "star": 6,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "42",
        "description": "寒婵在柳，十艺不成，意志薄弱之缺少专心数",
        "status": "吉多於凶",
        "hidden_info": "事业不专，十九不成，专心进取，可望成功",
        "shici": "十艺不成学艺真，博达艺能结果因，意志薄弱不取心，易于落陷心孤独。",
        "star": 4,
        "jianyi": "对人对事需要用心专一，以免贻误前程。",
        "result": "吉带凶",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "43",
        "description": "邪途散财，外祥内苦之夸大妄想数",
        "status": "凶多于吉",
        "hidden_info": "雨夜之花，外祥内苦，忍耐自重，转凶为吉",
        "shici": "雨夜之花是薄命，假虚假实影无踪，易失信用无地立，枯藤老树靠依难。",
        "star": 3,
        "jianyi": "需要注重个人私生活方面的修炼，以免贻误前程。",
        "result": "吉带凶",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "44",
        "description": "须眉难展，力量有限之悲哀续出数",
        "status": "大凶",
        "hidden_info": "虽用心计，事难遂愿，贪功好进，必招失败",
        "shici": "愁眉难展破家财，暗淡辛苦悲运来，配合不宜逆境临，远离颠倒正逢时。",
        "star": 1,
        "jianyi": "切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "45",
        "description": "难关衝破，顺风扬帆，新生泰和之万事如意数",
        "status": "中吉",
        "hidden_info": "杨柳遇春，绿叶发枝，冲破难关，一举成名",
        "shici": "新生泰运顺行舟，排除万难总无忧，成功繁荣四海明，荣华富贵好前程。",
        "star": 5,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "46",
        "description": "罗网系身之离祖成家数",
        "status": "大凶",
        "hidden_info": "坎坷不平，艰难重重，若无耐心，难望有成",
        "shici": "罗网系身汹运转，一生困苦殃变多，身病孤贫可难靠，得到平安船逆风。",
        "star": 1,
        "jianyi": "尤需注意个人安全，以免意外灾害对自己造成伤害。切忌沉迷投机，可免贻误前程。",
        "result": "凶",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "47",
        "description": "点铁成金，开花结果，永显名声之权威进取数",
        "status": "大吉",
        "hidden_info": "有贵人助，可成大业，或遇不济，浮沉不大",
        "shici": "开花结子衣食足，大业奏功可庆祝，子孙繁荣多快乐，一家圆满庆有馀。",
        "star": 6,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "48",
        "description": "青松方鹤，顾问尊敬，德智兼备之出身清贵数",
        "status": "大吉",
        "hidden_info": "美化丰实，鹤立鸡群，名利俱全，繁荣富贵",
        "shici": "有德且智德望高，堪为顾问得仁和，名利双收天赋富，威望荣达世间豪。",
        "star": 6,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "49",
        "description": "先吉后凶，吉凶难分之不断辛劳数",
        "status": "吉多於凶",
        "hidden_info": "遇吉则吉，遇凶则凶，惟靠谨慎，逢凶化吉",
        "shici": "吉凶难分运歧路，三才配置好鸿图，若逢凶星灾厄至，斜阳落夕苦难居。",
        "star": 4,
        "jianyi": "容易因异性而引发困扰，失利，而且一生常遇逆境之折磨。家庭和顺则万事可成。",
        "result": "凶",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "50",
        "description": "小舟入海，一成一败，吉凶参半，须防倾覆数",
        "status": "吉多於凶",
        "hidden_info": "吉凶互见，一成一败，凶中有吉，吉中有凶",
        "shici": "一成一败一瞬间，浮沉未定难得安，兴时不和平时好，败时始觉已致迟。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "51",
        "description": "盛衰交加，竭力经营之天运享受数",
        "status": "吉多于凶",
        "hidden_info": "一盛一衰，浮沉不常，自重自处，可保平安",
        "shici": "盛衰交加是运期，一时声名骤离分，平生远离风波路，到老免受灾祸图。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "52",
        "description": "先见之明，雨过天晴之理想实现数",
        "status": "大吉",
        "hidden_info": "草木逢春，雨过天晴，渡过难关，即获成功",
        "shici": "先见机明察佳期，意志坚固好运时，功名利达福禄全，一世荣隆乐绵绵。",
        "star": 6,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "53",
        "description": "忧愁困苦，先苦后甜之好景难长数",
        "status": "吉多于凶",
        "hidden_info": "盛衰参半，外祥内苦，先吉后凶，先凶后吉",
        "shici": "内心忧愁无人知，外盛内衰迫近期，恐防晚境心落薄，若逢幸运好护持。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "54",
        "description": "多难悲运，横灾变死之难望成功数",
        "status": "大凶",
        "hidden_info": "虽倾全力，难望成功，表相汹凶，最好改名",
        "shici": "多难非运亦障害，忧苦不和祸常来，枯藤老树温饱梦，远离颠倒是此时。",
        "star": 1,
        "jianyi": "尤需注意个人安全，以免意外灾害对自己造成伤害。",
        "result": "凶",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "55",
        "description": "外祥内苦，和顺不实，先苦后甘之信心成事数",
        "status": "吉多於凶",
        "hidden_info": "外观隆昌，内隐祸患，克服难关，开出泰运",
        "shici": "外美内苦时常悲，一面极盛一面衰，吉凶参半难以定，克服难关会运期。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "56",
        "description": "浪里行舟，历尽艰辛，暮日凄凉之四周障害数",
        "status": "大凶",
        "hidden_info": "事与愿违，终难成功，欲速不达，有始有终",
        "shici": "暮日凄凉事难成，进取心薄不安然，万事龃龉精力败，低调为人保家财。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "57",
        "description": "寒雪青松之最大荣运数",
        "status": "中吉",
        "hidden_info": "努力经营，时来运转，旷野枯草，春来花开",
        "shici": "寒雪青松性刚强，一度祸难过灾殃，将此发达利亨通，晚景繁荣福无疆。",
        "star": 5,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "58",
        "description": "晚行遇月，先苦后甘之宽宏扬名数",
        "status": "中吉",
        "hidden_info": "半凶半吉，浮沉多端，始凶终吉，能保成功",
        "shici": "先苦后甘费心思，难关渡过福人扶，终逢兴隆乐余庆，恰如甘蔗好尾甘。",
        "star": 5,
        "jianyi": "",
        "result": "凶带吉",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "59",
        "description": "寒婵悲风，时运不济，得亦再失之车轮无毅数",
        "status": "大凶",
        "hidden_info": "遇事犹疑，难望成事，大刀阔斧，始可有成",
        "shici": "车轮无毅不能行，失意逆境却难定，一旦厄来难伏起，果敢坚毅改前程。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "60",
        "description": "争名夺利，暗淡无光之福禄自失数",
        "status": "大凶",
        "hidden_info": "黑暗无光，心迷意乱，出尔反尔，难定方针",
        "shici": "灯微光弱步难行，苦厄刑伤事难成，体弱多病常困苦，徒加烦劳损精神。",
        "star": 1,
        "jianyi": "吉星甚少眷顾，且易累及他人，有浪费金钱之倾向，倒楣运强，需要注重修炼个人德行，以免因此受累。",
        "result": "凶",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "61",
        "description": "名利双收之修炼积德数",
        "status": "大吉",
        "hidden_info": "云遮半月，百隐风波，应自谨慎，始保平安",
        "shici": "名利双收富荣达，修身养德防未燃，傲慢不逊失人和，恐有家庭起风波。",
        "star": 6,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "62",
        "description": "基础虚弱之艰难困苦数",
        "status": "大凶",
        "hidden_info": "烦闷懊恼，事事难展，自防灾祸，始免困境",
        "shici": "基础虚弱重信用，不和衰败惹殃困，生涯苦楚因执起，步步留意保平安。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "63",
        "description": "富贵荣华，身心安泰之共同亲和数",
        "status": "大吉",
        "hidden_info": "万物化育，繁荣之象，专心一意，始能成功",
        "shici": "富贵荣达得显甯，子孙繁茂福绵绵，一身平安富益寿，福禄双全享千锺。",
        "star": 6,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "64",
        "description": "骨肉分离，孤儿悲愁，鸿运已逝之家运不幸数",
        "status": "大凶",
        "hidden_info": "见异思迁，十九不成，徒劳无功，回头是岸",
        "shici": "黄鹤如风难复来，浮沉破病难平安，非业困苦叹悲愁，远离颠倒寿更长。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "65",
        "description": "富贵长寿之光明正大数",
        "status": "中吉",
        "hidden_info": "吉运自来，能享盛名，把握机会，必获成功",
        "shici": "富贵长寿逢吉祥，家运隆昌喜气扬，福禄繁荣兼富贵，万事通达实贵重。",
        "star": 5,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "66",
        "description": "内外不和之多欲失福数",
        "status": "大凶",
        "hidden_info": "黑夜漫长，进退维谷，内外不合，信用缺乏",
        "shici": "内外不和不自由，进退两难总是忧，难苦虽灭艰难到，灾厄交加杯具来，心无梦想无所失。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "67",
        "description": "财路亨通，志气坚强之万商云集数",
        "status": "大吉",
        "hidden_info": "时来运转，事事如意，功成名就，富贵自来",
        "shici": "利路享通万事成，和畅逍达四海明，家运隆盛招富贵，万商云集得繁荣。",
        "star": 6,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "68",
        "description": "不失先机，宽容好运之兴家立业数",
        "status": "大吉",
        "hidden_info": "思虑周详，计划力行，不失先机，可望成功",
        "shici": "兴家立业意志强，智虑周密名望扬，志操坚固信用重，一身才艺建基业。",
        "star": 6,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "69",
        "description": "坐立不安之处世多难数",
        "status": "大凶",
        "hidden_info": "动摇不安，常陷逆境，不得时运，难得利润",
        "shici": "坐立不安如萍动，厄困事业逢波浪，废疾多病祸根至，精神意失易心狂。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "70",
        "description": "废物灭亡，家运衰退之晚景凄凉数",
        "status": "大凶",
        "hidden_info": "惨淡经营，难免贫困，希望不大，舍得求成",
        "shici": "废物灭亡不中用，一生平淡常困贫，忧苦离乱端数异，枝折果落重难长，心无挂碍无所得。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "71",
        "description": "正气堂堂，毫无实质，养神耐劳之耗神而劳数",
        "status": "吉多于凶",
        "hidden_info": "吉凶参半，惟赖勇气，贯彻力行，始可成功",
        "shici": "养神耐劳得安然，修身养德计谋成，若乏实行难成事，贯彻不怠始富荣。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    },
    {
        "number": "72",
        "description": "先甜后苦，万难艰辛之一败涂地数",
        "status": "凶多于吉",
        "hidden_info": "利害混集，害多利寡，得而复失，难以安顺",
        "shici": "未雨绸缪防未燃，外盛内衰难富乐，先苦后甘命运定，岂是人生不依强。",
        "star": 3,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "6",
        "personalityType": "做事喜好凭直觉型",
        "specificPerformance": "有特强的第六灵感，性格率直无机心，深得朋辈爱戴。感情路上多采多姿。做事喜好凭个人直觉及预感做决定。"
    },
    {
        "number": "73",
        "description": "志高力微之努力奋斗数",
        "status": "中吉",
        "hidden_info": "安乐自来，自然吉祥，力行不懈，终必成功",
        "shici": "志高力微乏实行，妄谋无计事难成，晚年安宁静逸祥，享得天赋增吉相。",
        "star": 5,
        "jianyi": "",
        "result": "吉",
        "personalityCoefficient": "7",
        "personalityType": "独断独行/吸引人型",
        "specificPerformance": "为人独断独行，事事自行作主解决，鲜有求助他人。而这份独立个性，正正就是吸引异性的特质。但其实心底里，却是渴望有人可让他/她依赖。"
    },
    {
        "number": "74",
        "description": "沉沦逆境之秋叶落寞数",
        "status": "大凶",
        "hidden_info": "利不及费，坐食山空，如无智谋，难望成功",
        "shici": "沉沦逆境无智能，坐吃山空难有成，落日景悲难渡日，奈何悲运悟今生，无有恐怖无所得。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "8",
        "personalityType": "热情/善变梦想家型",
        "specificPerformance": "对人热情无遮掩，时常梦想可以谈一场戏剧性恋爱，亲身体会个中悲欢离合的动人经历，是个大梦想家。但对于感情却易变卦。"
    },
    {
        "number": "75",
        "description": "守者可安，发迹甚迟之利害分明数",
        "status": "吉多于凶",
        "hidden_info": "吉中带凶，欲速不达，进不如守，可保安详",
        "shici": "守则可安无忧事，龃龉失意害自私，妄进大败厄近身，三思后行皆安然。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "9",
        "personalityType": "自我牺牲/性格被动型",
        "specificPerformance": "惯于无条件付出，从不祈求有回报，有为了成全他人不惜牺牲自己的情操。但讲到本身的爱情观，却流于被动，往往因为内敛而错过大好姻缘。"
    },
    {
        "number": "76",
        "description": "倾覆离散，虽劳无功之财破落日数",
        "status": "大凶",
        "hidden_info": "表相汹凶，破败之象，能用不用，以避厄运",
        "shici": "倾覆离散居财破，内外不和难可靠，空山鸟飞愁悲叹，贫病交迫寿难延，远离颠倒宜及早。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "1",
        "personalityType": "要面包不要爱情型",
        "specificPerformance": "责任心重，尤其对工作充满热诚，是个彻头彻尾工作狂。但往往因为过分专注职务，而忽略身边的家人及朋友，是个宁要面包不需要爱情的理性主义者。"
    },
    {
        "number": "77",
        "description": "家庭有悦，半吉半凶，乐极生悲之多劳衰歎数",
        "status": "吉多于凶",
        "hidden_info": "先苦后甘，先甘后苦，如能守成，不致失败",
        "shici": "乐极生悲吉藏凶，长上馀德福禄强，前佳后劣悲叹运，中年苦劳晚年荣。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "2",
        "personalityType": "不善表达/疑心大型",
        "specificPerformance": "在乎身边各人对自己的评价及观感，不善表达个人情感，是个先考虑别人感受，再作出相应配合的内敛一族。对于爱侣，经常存有怀疑之心。"
    },
    {
        "number": "78",
        "description": "先吉后凶，壮年渐败数，晚境凄凉之功德光荣数",
        "status": "吉多于凶",
        "hidden_info": "有得有失，华而不实，须防劫财，始保平安",
        "shici": "青年中年皆发达，壮年渐感不景气，华而不实晚运弱，心无挂碍无所失。",
        "star": 4,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "3",
        "personalityType": "大胆行事冲动派型",
        "specificPerformance": "爱好追寻刺激，有不理后果大胆行事的倾向。崇尚自由奔放的恋爱，会拼尽全力爱一场，是就算明知无结果都在所不惜的冲动派。"
    },
    {
        "number": "79",
        "description": "受人压制，挽回乏力之身疲力尽数",
        "status": "大凶",
        "hidden_info": "如走夜路，前途无光，希望不大，劳而无功",
        "shici": "挽回乏力困善谋，精神不定如暗云，失节丧信无所止，放下我执事可成。",
        "star": 1,
        "jianyi": "",
        "result": "凶",
        "personalityCoefficient": "4",
        "personalityType": "高度戒备难交心型",
        "specificPerformance": "经常处于戒备状态，对任何事都没法放松处理，孤僻性情难以交朋结友。对于爱情，就更加会慎重处理。任何人必须经过你长期观察及通过连番考验，方会减除戒备与你交往。"
    },
    {
        "number": "80",
        "description": "凶星入度，清本缩小，一生皆苦之孤独空虚数",
        "status": "大凶",
        "hidden_info": "得而复失，枉费心机，守成无贪，可保安稳",
        "shici": "劳而无得费心机，终生困苦与劳动，障碍病难常不绝，修养善德小安康。",
        "star": 1,
        "jianyi": "",
        "result": "吉带凶",
        "personalityCoefficient": "5",
        "personalityType": "好奇心旺求知欲强型",
        "specificPerformance": "好奇心极度旺盛，求知欲又强，有打烂沙盘问到笃的锲而不舍精神。此外，你天生有语言天分，学习外文比一般人更易掌握。"
    }
]


function calculateNumber(input) {
    // 将输入转换为字符串并截取最后四位
    let lastFourDigits = input.toString().slice(-4);
    
    // 将最后四位转换为整数
    let number = parseInt(lastFourDigits, 10);
    
    // 将数字除以80并减去整数部分，只保留小数部分
    let fractionalPart = (number / 80) - Math.floor(number / 80);
    
    // 将小数部分乘以80并取整
    let result = Math.floor(fractionalPart * 80);
    
    return result;
  }
  export  {
    arr1,arr2,calculateNumber
  }