const models =  [
  {
    "label": "Tiny",
    "value": "ggml-tiny.bin",
    "size": "77.7 MB",
    "description": "model.tiny description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin",
    "speed": 6,
    "speedLabel": "common.fast",
    "speedValue": "fast",
    "quality": 2,
    "download": false,
    "lang": "multi",
    "langLabel": "model.multi language",
    "sha": "bd577a113a864445d4c299885e0cb97d4ba92b5f"
  },
  {
    "label": "Tiny.en",
    "value": "ggml-tiny.en.bin",
    "size": "77.7 MB",
    "description": "model.tiny description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin",
    "speed": 6,
    "speedLabel": "common.fast",
    "speedValue": "fast",
    "quality": 2,
    "download": false,
    "lang": "en",
    "langLabel": "model.only english",
    "sha": "c78c86eb1a8faa21b369bcd33207cc90d64ae9df"
  },
  {
    "label": "Base",
    "value": "ggml-base.bin",
    "size": "148 MB",
    "description": "model.base description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin",
    "speed": 5,
    "speedLabel": "common.fast",
    "speedValue": "fast",
    "quality": 3,
    "download": false,
    "lang": "multi",
    "langLabel": "model.multi language",
    "sha": "465707469ff3a37a2b9b8d8f89f2f99de7299dac"
  },
  {
    "label": "Base.en",
    "value": "ggml-base.en.bin",
    "size": "148 MB",
    "description": "model.base description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin",
    "speed": 5,
    "speedLabel": "common.fast",
    "speedValue": "fast",
    "quality": 3,
    "download": false,
    "lang": "en",
    "langLabel": "model.only english",
    "sha": "137c40403d78fd54d454da0f9bd998f78703390c"
  },
  {
    "label": "Small",
    "value": "ggml-small.bin",
    "size": "488 MB",
    "description": "model.small description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin",
    "speed": 4,
    "speedLabel": "common.balance",
    "speedValue": "balance",
    "quality": 4,
    "download": false,
    "lang": "multi",
    "langLabel": "model.multi language",
    "sha": "55356645c2b361a969dfd0ef2c5a50d530afd8d5"
  },
  {
    "label": "Small.en",
    "value": "ggml-small.en.bin",
    "size": "488 MB",
    "description": "model.small description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin",
    "speed": 4,
    "speedLabel": "common.balance",
    "speedValue": "balance",
    "quality": 4,
    "download": false,
    "lang": "en",
    "langLabel": "model.only english",
    "sha": "db8a495a91d927739e50b3fc1cc4c6b8f6c2d022"
  },
  {
    "label": "Medium",
    "value": "ggml-medium.bin",
    "size": "1.53 GB",
    "description": "model.medium description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin",
    "speed": 3,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 5,
    "download": false,
    "lang": "multi",
    "langLabel": "model.multi language",
    "sha": "fd9727b6e1217c2f614f9b698455c4ffd82463b4"
  },
  {
    "label": "Medium.en",
    "value": "ggml-medium.en.bin",
    "size": "1.53 GB",
    "description": "model.medium description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.en.bin",
    "speed": 3,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 5,
    "download": false,
    "lang": "en",
    "langLabel": "model.only english",
    "sha": "8c30f0e44ce9560643ebd10bbe50cd20eafd3723"
  },
  {
    "label": "Large(v1)",
    "value": "ggml-large-v1.bin",
    "size": "3.09 GB",
    "description": "model.large description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v1.bin",
    "speed": 2,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 6,
    "download": false,
    "lang": "multi",
    "langLabel": "model.multi language",
    "sha": "b1caaf735c4cc1429223d5a74f0f4d0b9b59a299"
  },
  {
    "label": "Large(v2)",
    "value": "ggml-large-v2.bin",
    "size": "3.09 GB",
    "description": "model.large description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v2.bin",
    "speed": 2,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 6,
    "download": false,
    "lang": "multi",
    "langLabel": "model.multi language",
    "sha": "0f4c8e34f21cf1a914c59d8b3ce882345ad349d6"
  },
  {
    "label": "Large(v3)",
    "value": "ggml-large-v3.bin",
    "size": "3.09 GB",
    "description": "model.large description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3.bin",
    "speed": 2,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 6,
    "download": false,
    "lang": "multi",
    "langLabel": "model.multi language",
    "sha": "ad82bf6a9043ceed055076d0fd39f5f186ff8062"
  },
  {
    "label": "Distil Large(v3)",
    "value": "ggml-distil-large-v3.bin",
    "size": "1.52 GB",
    "description": "model.large description",
    "disabled": true,
    "downloadLink": "https://huggingface.co/distil-whisper/distil-large-v3-ggml/resolve/main/ggml-distil-large-v3.bin?download=true",
    "speed": 2,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 6,
    "download": false,
    "lang": "en",
    "langLabel": "model.only english",
    "sha": "5e61e98bdcf3b9a78516c59bf7d1a10d64cae67a"
  },
  {
    "label": "Memo-large.zh",
    "value": "Memo-large.zh.bin",
    "size": "2.88 GB",
    "description": "model.large description",
    "disabled": true,
    "downloadLink": "https://model.memo.ac/Memo-large.zh.bin",
    "speed": 2,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 6,
    "download": false,
    "lang": "zh",
    "langLabel": "model.only chinese",
    "sha": "83a078eda99ed389b1f9879c615b9e70e492f878"
  },
  {
    "label": "Memo-large.ja",
    "value": "Memo-large.ja.bin",
    "size": "2.88 GB",
    "description": "model.large description",
    "disabled": true,
    "downloadLink": "https://model.memo.ac/Memo-large.ja.bin",
    "speed": 2,
    "speedLabel": "common.high quality",
    "speedValue": "quality",
    "quality": 6,
    "download": false,
    "lang": "ja",
    "langLabel": "model.only japanese",
    "sha": "1f21b278e829dcba02fb820d8434a36738cf0aef"
  }
]

export default models